FROM python:3.9.5-buster

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
         python3 \
         python3-dev \
         python3-pip \
         python3-wheel \
         uwsgi \
         uwsgi-plugin-python3 \
         libpcre3-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install setuptools

RUN mkdir -p /code/howdareyou
WORKDIR /code/howdareyou
COPY requirements.txt /code/howdareyou
RUN pip3 install -r requirements.txt

RUN apt-get purge -y build-essential && \
    apt-get autoremove -y && \
    apt-get clean -y

WORKDIR /code/howdareyou
#COPY . /code/howdareyou

ENV FLASK_APP=howdareyou/app.py
ENV FLASK_ENV=debugging
ENV FLASK_DEBUG=1
ENV FLASK_RUN_HOST=0.0.0.0
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
CMD flask run
